title: <p align= "center"> Nizam Sharif </p>
logo: /assets/img/logo.png

description: Minimal is a theme for GitHub Pages.
  <p align= "center">
  <a href= "https://github.com/nizamsharif">GitHub</a>
  I'm working on Data Science, Machine Learning & NLP related problems.
  </p>



theme: jekyll-theme-minimal
